create extension if not exists pgcrypto;
create type app_role as enum ('Super Admin','Operations','TSS Officer','Field Technician','Finance','Viewer');
create type record_status as enum ('Pending','In Progress','Completed','Cancelled','Overdue');

create table if not exists profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text not null,email text not null unique,role app_role not null default 'Viewer',active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists clients(id uuid primary key default gen_random_uuid(),client_code text unique,name text not null,contact_person text,phone text,email text,location text,category text,status text default 'Active',notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists jobs(id uuid primary key default gen_random_uuid(),job_id text not null unique,client_id uuid references clients(id),job_type text,number_of_vehicles integer not null default 1,vehicle_make text,scheduled_date date,location text,tss_officer_id uuid references profiles(id),assigned_technician_id uuid references profiles(id),priority text default 'Normal',status record_status not null default 'Pending',description text,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists vehicles(id uuid primary key default gen_random_uuid(),job_id uuid not null references jobs(id) on delete cascade,registration text,vehicle_make text,vehicle_details text,status text default 'Pending',created_at timestamptz not null default now());
create table if not exists job_completions(id uuid primary key default gen_random_uuid(),job_id uuid references jobs(id) on delete set null,vehicle_id uuid references vehicles(id) on delete set null,device_id text,completion_date date,installer text,location text,client text,vehicle_details text,vehicle_make text,status text default 'Completed',tss_officer text,remarks text,created_at timestamptz not null default now());
create table if not exists stock_transactions(id uuid primary key default gen_random_uuid(),job_id uuid references jobs(id) on delete set null,vehicle_id uuid references vehicles(id) on delete set null,network text,device_type text,device_status text,device_id text,sim_id text,date_collected date,operations_remark text,operations_correction text,date_issued date,date_installed date,installer text,location text,client text,vehicle_details text,vehicle_make text,other_issues text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists miscellaneous_charges(id uuid primary key default gen_random_uuid(),charge_id text not null unique,job_id uuid references jobs(id) on delete set null,client_id uuid references clients(id) on delete set null,location text,logistics numeric(12,2) default 0,accommodation numeric(12,2) default 0,swap numeric(12,2) default 0,deinstallation numeric(12,2) default 0,reinstallation numeric(12,2) default 0,health_check numeric(12,2) default 0,sim_replacement numeric(12,2) default 0,others numeric(12,2) default 0,paid_or_approved text default 'Pending',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists tasks(id uuid primary key default gen_random_uuid(),task_id text not null unique,title text not null,description text,assigned_to uuid references profiles(id),created_by uuid references profiles(id),department text,priority text default 'Normal',due_at timestamptz,status record_status not null default 'Pending',completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists task_comments(id uuid primary key default gen_random_uuid(),task_id uuid not null references tasks(id) on delete cascade,user_id uuid references profiles(id),comment text not null,created_at timestamptz not null default now());
create table if not exists reminders(id uuid primary key default gen_random_uuid(),title text not null,details text,user_id uuid references profiles(id),remind_at timestamptz not null,sent_at timestamptz,created_at timestamptz not null default now());
create table if not exists audit_logs(id bigint generated by default as identity primary key,actor_id uuid references profiles(id),action text not null,module text not null,record_id text,details jsonb,created_at timestamptz not null default now());
create table if not exists google_connections(id uuid primary key default gen_random_uuid(),module text not null unique,spreadsheet_id text not null,sheet_name text,sync_direction text not null default 'platform_to_sheet',last_sync_at timestamptz,last_error text,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create index if not exists jobs_assigned_technician_idx on jobs(assigned_technician_id);
create index if not exists jobs_scheduled_date_idx on jobs(scheduled_date);
create index if not exists job_completions_device_id_idx on job_completions(device_id);
create index if not exists stock_transactions_device_id_idx on stock_transactions(device_id);
create index if not exists stock_transactions_sim_id_idx on stock_transactions(sim_id);
create index if not exists tasks_assigned_to_idx on tasks(assigned_to);
create index if not exists audit_logs_created_at_idx on audit_logs(created_at desc);

do $$ declare t text; begin foreach t in array array['profiles','clients','jobs','vehicles','job_completions','stock_transactions','miscellaneous_charges','tasks','task_comments','reminders','audit_logs','google_connections'] loop execute format('alter table %I enable row level security',t); end loop; end $$;

create or replace function public.current_app_role() returns app_role language sql stable security definer set search_path=public as $$ select role from public.profiles where id=auth.uid() and active=true limit 1 $$;
create or replace function public.is_super_admin() returns boolean language sql stable security definer set search_path=public as $$ select coalesce(public.current_app_role()='Super Admin',false) $$;
create or replace function public.bootstrap_first_super_admin(p_full_name text,p_email text) returns profiles language plpgsql security definer set search_path=public as $$ declare p profiles; begin if exists(select 1 from public.profiles) then raise exception 'Initial Super Admin has already been created'; end if; if auth.uid() is null then raise exception 'Authentication is required'; end if; insert into public.profiles(id,full_name,email,role,active) values(auth.uid(),p_full_name,p_email,'Super Admin',true) returning * into p; return p; end $$;

create or replace function public.enforce_field_restrictions() returns trigger language plpgsql security definer set search_path=public as $$
begin
  if tg_table_name='jobs' and public.current_app_role()='TSS Officer' then
    if new.assigned_technician_id is distinct from old.assigned_technician_id then raise exception 'TSS Officer cannot change Techie Assigned'; end if;
  elsif tg_table_name='stock_transactions' then
    if public.current_app_role()='Operations' then
      if new.device_id is distinct from old.device_id or new.sim_id is distinct from old.sim_id or new.date_issued is distinct from old.date_issued then raise exception 'Operations cannot change Device ID, SIM ID or Date Issued'; end if;
    elsif public.current_app_role()='Finance' then
      if new.job_id is distinct from old.job_id or new.vehicle_id is distinct from old.vehicle_id or new.network is distinct from old.network or new.device_type is distinct from old.device_type or new.device_status is distinct from old.device_status or new.date_collected is distinct from old.date_collected or new.operations_remark is distinct from old.operations_remark or new.operations_correction is distinct from old.operations_correction or new.date_installed is distinct from old.date_installed or new.installer is distinct from old.installer or new.location is distinct from old.location or new.client is distinct from old.client or new.vehicle_details is distinct from old.vehicle_details or new.vehicle_make is distinct from old.vehicle_make or new.other_issues is distinct from old.other_issues then raise exception 'Finance may only change Device ID, SIM ID and Date Issued'; end if;
    end if;
  elsif tg_table_name='job_completions' and public.current_app_role()='Operations' then
    if new.job_id is distinct from old.job_id or new.vehicle_id is distinct from old.vehicle_id or new.device_id is distinct from old.device_id or new.completion_date is distinct from old.completion_date or new.installer is distinct from old.installer or new.location is distinct from old.location or new.client is distinct from old.client or new.vehicle_details is distinct from old.vehicle_details or new.vehicle_make is distinct from old.vehicle_make or new.status is distinct from old.status or new.tss_officer is distinct from old.tss_officer then raise exception 'Operations may only add or edit a remark on Daily Job Done'; end if;
  end if;
  return new;
end $$;

drop trigger if exists jobs_field_restrictions on jobs;
create trigger jobs_field_restrictions before update on jobs for each row execute function public.enforce_field_restrictions();
drop trigger if exists stock_field_restrictions on stock_transactions;
create trigger stock_field_restrictions before update on stock_transactions for each row execute function public.enforce_field_restrictions();
drop trigger if exists completion_field_restrictions on job_completions;
create trigger completion_field_restrictions before update on job_completions for each row execute function public.enforce_field_restrictions();

do $$ declare r record; begin for r in select policyname,tablename from pg_policies where schemaname='public' and tablename in ('profiles','clients','jobs','vehicles','job_completions','stock_transactions','miscellaneous_charges','tasks','task_comments','reminders','audit_logs','google_connections') loop execute format('drop policy if exists %I on %I',r.policyname,r.tablename); end loop; end $$;

create policy profiles_select on profiles for select to authenticated using (true);
create policy profiles_admin_insert on profiles for insert to authenticated with check (public.is_super_admin());
create policy profiles_admin_update on profiles for update to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
create policy profiles_admin_delete on profiles for delete to authenticated using (public.is_super_admin());

create policy clients_select on clients for select to authenticated using (true);
create policy clients_insert on clients for insert to authenticated with check (public.current_app_role() in ('Super Admin','TSS Officer'));
create policy clients_update on clients for update to authenticated using (public.current_app_role() in ('Super Admin','TSS Officer')) with check (public.current_app_role() in ('Super Admin','TSS Officer'));
create policy clients_delete on clients for delete to authenticated using (public.is_super_admin());

create policy jobs_select on jobs for select to authenticated using (true);
create policy jobs_insert on jobs for insert to authenticated with check (public.current_app_role() in ('Super Admin','TSS Officer'));
create policy jobs_update on jobs for update to authenticated using (public.current_app_role() in ('Super Admin','TSS Officer')) with check (public.current_app_role() in ('Super Admin','TSS Officer'));
create policy jobs_delete on jobs for delete to authenticated using (public.is_super_admin());

create policy vehicles_select on vehicles for select to authenticated using (true);
create policy vehicles_insert on vehicles for insert to authenticated with check (public.current_app_role() in ('Super Admin','TSS Officer'));
create policy vehicles_update on vehicles for update to authenticated using (public.current_app_role() in ('Super Admin','TSS Officer')) with check (public.current_app_role() in ('Super Admin','TSS Officer'));
create policy vehicles_delete on vehicles for delete to authenticated using (public.is_super_admin());

create policy completions_select on job_completions for select to authenticated using (true);
create policy completions_insert on job_completions for insert to authenticated with check (public.current_app_role() in ('Super Admin','TSS Officer'));
create policy completions_update on job_completions for update to authenticated using (public.current_app_role() in ('Super Admin','TSS Officer','Operations')) with check (public.current_app_role() in ('Super Admin','TSS Officer','Operations'));
create policy completions_delete on job_completions for delete to authenticated using (public.is_super_admin());

create policy stock_select on stock_transactions for select to authenticated using (true);
create policy stock_insert on stock_transactions for insert to authenticated with check (public.is_super_admin());
create policy stock_update on stock_transactions for update to authenticated using (public.current_app_role() in ('Super Admin','Operations','Finance')) with check (public.current_app_role() in ('Super Admin','Operations','Finance'));
create policy stock_delete on stock_transactions for delete to authenticated using (public.is_super_admin());

create policy charges_select on miscellaneous_charges for select to authenticated using (true);
create policy charges_insert on miscellaneous_charges for insert to authenticated with check (public.current_app_role() in ('Super Admin','TSS Officer'));
create policy charges_update on miscellaneous_charges for update to authenticated using (public.current_app_role() in ('Super Admin','TSS Officer')) with check (public.current_app_role() in ('Super Admin','TSS Officer'));
create policy charges_delete on miscellaneous_charges for delete to authenticated using (public.is_super_admin());

create policy tasks_select on tasks for select to authenticated using (public.is_super_admin() or assigned_to=auth.uid() or public.current_app_role()='Viewer');
create policy tasks_insert on tasks for insert to authenticated with check (public.is_super_admin());
create policy tasks_update on tasks for update to authenticated using (public.is_super_admin() or assigned_to=auth.uid()) with check (public.is_super_admin() or assigned_to=auth.uid());
create policy tasks_delete on tasks for delete to authenticated using (public.is_super_admin());

create policy task_comments_select on task_comments for select to authenticated using (true);
create policy task_comments_insert on task_comments for insert to authenticated with check (user_id=auth.uid() or public.is_super_admin());

create policy reminders_select on reminders for select to authenticated using (user_id=auth.uid() or public.is_super_admin());
create policy reminders_insert on reminders for insert to authenticated with check (public.is_super_admin());
create policy reminders_update on reminders for update to authenticated using (public.is_super_admin());
create policy reminders_delete on reminders for delete to authenticated using (public.is_super_admin());

create policy audit_select on audit_logs for select to authenticated using (public.is_super_admin());
create policy audit_insert on audit_logs for insert to authenticated with check (public.is_super_admin());

create policy google_select on google_connections for select to authenticated using (public.is_super_admin());
create policy google_write on google_connections for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
